server:
  port: 9091
  servlet:
    context-path: /

spring:
  freemarker:
    cache: false
    request-context-attribute: request
    charset: UTF-8
    check-template-location: true
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .ftl
    settings:
      number_format: 0.##

  http:
    encoding:
      force-response: true

  redis:
    #redis单机配置
    host: 127.0.0.1
    port: 6379
    # 选择redis的数据库的分库
    database: 0
    #redis连接池配置
    lettuce:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 3000ms
  session:
    store-type: redis
    timeout: PT2M    #默认30M 超时时间
    redis:
      namespace: webtest:session
    cookie:
      timeout: PT2M

  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #基本属性
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/certificate_authority?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #监控统计拦截的filters
      filters: stat
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count:countSql